### ISSUE TITLE
Do you have paln to release ROS Melodic Version?

### ISSUE THREAD

**Issue by Joy-Zhang-0303** [project-srs/ros_lecture#1]
Hello, project-src,

I have been studying ROS by your lecture for a long time. The lecture material is good and useful.
One issue confusing me that is: my OS is Ubuntu18.04, and ROS is Melodic.
So, some projects can not compile succefully(Eg, nav_lecture)
**Considering the OS upgrading and ROS version upgrading, do you have plans to maintain and upgrade these lectures for newer Ubuntu > 16.04 and ROS > Kinetic ?**
![Screenshot from 2020-07-16 22-31-21](https://user-images.githubusercontent.com/48177679/87676900-1f379b00-c7b4-11ea-87e1-b2142a19ea56.png)

**Comment by project-srs** [comment]
Thank you for comment.
It already use with melodic.
https://travis-ci.org/github/project-srs/ros_lecture/builds/722186026
