### ISSUE TITLE
18 Rviz上で移動ロボットを作る　について

### ISSUE THREAD

**Issue by ba2vwbus13** [project-srs/ros_lecture#2]
これを実行した時、Rvizで次のエラーメッセージが表示されます。
Fixed Frame [world] does not exist

urdf/move_robot.urdfの中の
＜joint name="base_joint" type="floating"＞を
＜joint name="base_joint" type="fixed"＞にすればエラーは無くなりますが、
当然ロボットは動かなくなります。

原因がわかりますでしょうか？

**Comment by project-srs** [comment]
vis_robot_simというノードが立ち上がっていない可能性があります。
実行時の`rosnode list`の結果と`rosrun_tf view_frame`で生成されるpdfを張ってください。

**Comment by project-srs** [comment]
時間がたってのでclose
