### ISSUE TITLE
URDF内のアルファ値の設定について

### ISSUE THREAD

**Issue by ssr-yuki** [project-srs/ros_lecture#5]
こんにちは，はじめまして．
Qiitaの記事を拝読して気付いた点を述べさせていただきます．
（宗教上の理由によりQiitaのアカウントを作らないためこちらで失礼します．）

公式ドキュメント（http://wiki.ros.org/urdf/XML/link）によりますと，visual->material->colorタグにて指定するアルファ値の値も，RGB各値と同様，0.0-1.0の範囲に収まっている必要があります．

したがって，以下の貴記事や，サンプルコード（例えば以下の引用）では，厳密な意味では規格外のアルファ値を設定しているかと思われます．

https://qiita.com/srs/items/35bbaadd6c4be1e39bb9

https://github.com/project-srs/ros_lecture/blob/c28191a0278562f66178262b417b0fc96ae709c2/vis_lecture/urdf/move_robot.urdf#L2-L7

以上，細かいところで恐れ入りますが，ご確認いただければと思います．

**Comment by project-srs** [comment]
過去に何か誤解して誤設定したみたいです。以下のcommitで修正しました。
https://github.com/project-srs/ros_lecture/commit/dfb559e3fd8da54422f897934117d9a529594113

**Comment by ssr-yuki** [comment]
ご対応ありがとうございました！
